name: leafmap
channels:
    - conda-forge
dependencies:
    - nodejs=14.11
    - ipyleaflet>=0.14.0
    - jupyterlab=3
    - datapane
    - folium
    - gdal
    - imageio
    - keplergl
    - leafmap
    - localtileserver
    - palettable
    - pip
    - pydeck
    - xarray_leaflet
    - geopandas
    - osmnx
    - tifffile
