name: leafmap
channels:
    - conda-forge
dependencies:
    - nodejs=14.11
    - ipyleaflet=0.13.6
    - jupyterlab=3
    - datapane
    - folium=0.11.0
    - keplergl
    - leafmap=0.5.0
    - xarray_leaflet
    - geopandas
    - osmnx
