site_name: leafmap

site_url: https://leafmap.org

repo_url: https://github.com/giswqs/leafmap

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# google_analytics:
#     - UA-XXXXXXXXX-X
#     - auto

nav:
    - Home: index.md
    - Installation: installation.md
    - Get Started: get-started.md
    - Usage: usage.md
    - Tutorials: tutorials.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - YouTube Channel: https://www.youtube.com/c/QiushengWu
    - Report Issues: https://github.com/giswqs/leafmap/issues
    - API Reference:
          - basemaps module: basemaps.md
          - colormaps module: colormaps.md
          - common module: common.md
          - foliumap module: foliumap.md
          - leafmap module: leafmap.md
          - legends module: legends.md
          - toolbar module: toolbar.md
    - Notebooks:
          - notebooks/01_leafmap_intro.ipynb
          - notebooks/02_using_basemaps.ipynb
          - notebooks/03_cog_stac.ipynb
          - notebooks/04_cog_mosaic.ipynb
          - notebooks/05_load_raster.ipynb
          - notebooks/06_legend.ipynb
          - notebooks/07_colorbar.ipynb
          - notebooks/08_whitebox.ipynb
          - notebooks/09_csv_to_points.ipynb
          - notebooks/10_add_vector.ipynb
          - notebooks/11_linked_maps.ipynb
          - notebooks/12_split_map.ipynb
          - notebooks/13_add_osm.ipynb
